### ISSUE TITLE
Shop prices are insane >:(

### ISSUE THREAD

**Issue by alanlichen** [cursorweb/Cycle-Bot-Game#17]
**Is your feature request related to a problem? Please describe.**
The last few items in the shop are **almost** impossible to get.

**Describe the solution you'd like**
Please lower the prices of them and make a specific equation to calculate both tpc and cost.

**Describe alternatives you've considered**
Idk any alternatives smh

**Additional context**
![image](https://user-images.githubusercontent.com/40917647/110183207-3b2f9180-7dc3-11eb-906b-f1c234915522.png)
![image](https://user-images.githubusercontent.com/40917647/110183228-42569f80-7dc3-11eb-8109-3605460dd72a.png)

**Comment by alanlichen** [comment]
Does anyone want light mode screenshots? :p

**Comment by Codemonkey51** [comment]
> Does anyone want light mode screenshots? :p

I'm fine with a dark mode one ;)

**Comment by cursorweb** [comment]
yes they are supposed to get exponentially harder to obtain, you can look at the desmos graph
https://www.desmos.com/calculator/a52lf6eptr

**Comment by Codemonkey51** [comment]
> yes they are supposed to get exponentially harder to obtain, you can look at the desmos graph
> https://www.desmos.com/calculator/6y7siv8gqo

~~Cookie can do math :O~~ cool, I think if I rub my 2 brain cells together enough I might be able to understand that graph

**Comment by cursorweb** [comment]
> > yes they are supposed to get exponentially harder to obtain, you can look at the desmos graph
> > https://www.desmos.com/calculator/6y7siv8gqo
> 
> ~Cookie can do math :O~ cool, I think if I rub my 2 brain cells together enough I might be able to understand that graph

thanks i wrote it myself!

**Comment by Codemonkey51** [comment]
> > > yes they are supposed to get exponentially harder to obtain, you can look at the desmos graph
> > > https://www.desmos.com/calculator/6y7siv8gqo
> > 
> > 
> > ~Cookie can do math :O~ cool, I think if I rub my 2 brain cells together enough I might be able to understand that graph
> 
> thanks i wrote it myself!

How am I supposed to understand that graph tho?

**Comment by cursorweb** [comment]
> > > > yes they are supposed to get exponentially harder to obtain, you can look at the desmos graph
> > > > https://www.desmos.com/calculator/6y7siv8gqo
> > > 
> > > 
> > > ~Cookie can do math :O~ cool, I think if I rub my 2 brain cells together enough I might be able to understand that graph
> > 
> > 
> > thanks i wrote it myself!
> 
> How am I supposed to understand that graph tho?

x: the amount given
y: the price

**Comment by alanlichen** [comment]
> > Does anyone want light mode screenshots? :p
> 
> I'm fine with a dark mode one ;)

alr cool 
![image](https://user-images.githubusercontent.com/40917647/110189199-2b1fae00-7dd3-11eb-9b3d-6543b96c1fad.png)

**Comment by cursorweb** [comment]
uh if there isn't going to be any more discussion I'll close this
