### ISSUE TITLE
Lore system

### ISSUE THREAD

**Issue by Codemonkey51** [cursorweb/Cycle-Bot-Game#18]
**Is your feature request related to a problem? Please describe.**
A system to deliver the lore to cycle bot users

**Describe the solution you'd like**
Display the lore to users when they "unlock something", like on first code, send embed with lore, first craft, etc...

**Describe alternatives you've considered**
None.

**Additional context**
No.

**Comment by cursorweb** [comment]
alright
nice idea

I feel like perhaps a centralized lore command that can be unlocked based on level would be better, however.

**Comment by Codemonkey51** [comment]
> alright
> nice idea
> 
> I feel like perhaps a centralized lore command that can be unlocked based on level would be better, however.

Maybe an embed saying:
```
you have unlocked the lore for `x`, you can do `&lore x` to view it.
```

**Comment by cursorweb** [comment]
alright
but that's each level up so yeah cool!

**Comment by Codemonkey51** [comment]
@cursorweb should I use discussions for an idea for a new mechanic, I think it would fit better their (since it's just an idea, not a full feature request)

**Comment by cursorweb** [comment]
yeah sure that would be nice

**Comment by brokentoken5** [comment]
this is cool

**Comment by staticalliam7** [comment]
jeff lore

**Comment by cursorweb** [comment]
okay i've decided to abandon the lore aspect of cycle, there isn't much worldbuilding anyways so the only lore would be the item descriptions. There's no need for a separate command for this.
