### ISSUE TITLE
Major Update

### ISSUE THREAD

**Issue by cursorweb** [cursorweb/Cycle-Bot-Game#28]
This is the major update of cycle bot since v0.1. After much thought,

I will now be primarily focusing on:
- [x] Working boosts System
  - [x] Temporarily buff someone's stats
  - [x] Spell system @Codemonkey51
    - [x] Inspired by the bots, you can use this for enhanced buffs at the cost of a 25% chance of **backfiring**
  - [x] Obtainable through items or drops only. Can be crafted.
- [x] Rebalancing many many things
- [x] Add many many new items
  - [x] Add 4+ pages worth
- [ ] Add prestige @alanlichen once you get to 1T cycles I will consider actually implementing
- [x] Redesign deteriorating code
- [x] Improve code quality through eslint
- [x] No cooldown when the command entered was invalid
- [ ] Show your rank on the leaderboard if you are not on the first page

**Comment by cursorweb** [comment]
edit: prestige is being added when it is.

**Comment by alanlichen** [comment]
Just for reference currently i have 390m cycles
![image](https://user-images.githubusercontent.com/40917647/112033269-7c7dac00-8afa-11eb-8aa6-37d473d36ae2.png)

**Comment by darkdarcool** [comment]
lol nice

**Comment by cursorweb** [comment]
ok i'll put this into the next update, there's a few more things yet to add

**Comment by darkdarcool** [comment]
Ok

**Comment by cursorweb** [comment]
by the way
what do you think about the chests

do they give too many items

**Comment by darkdarcool** [comment]
I haven't tried them yet, in 30 min I can test

**Comment by darkdarcool** [comment]
lemme test on discord now

**Comment by darkdarcool** [comment]
It's a good amount!
