### ISSUE TITLE
Newest Commit broke several commands within the command handler

### ISSUE THREAD

**Issue by AltariasMainAccount** [cursorweb/Cycle-Bot-Game#37]
**Describe the bug**
When you use certain commands the bot will receive an unhandled exception error:
`TypeError: Cannot read property 'names' of undefined` at `line 55` of `index.ts`

**To Reproduce**
I have not tried every command but 2 of the ones that do give that error are `&balance` and `&profile`

**Expected behavior**
The commands should be able to run nonetheless.

**Behavior observed**
`TypeError: Cannot read property 'names' of undefined` at `line 55` of `index.ts`
The command does not run.

**Screenshots**
There is no screenshots. You have to reproduce the issue yourself.

**Contact Information**
There is no need to restore my data, but my contact information is still `Cyanide#8020`

**Comment by AltariasMainAccount** [comment]
I suspect that when the developer updated the commands to support the boosts, they accidentally caused some issue within the command itself. Other commands can run fine. (Like `&post` and `&code`)

List of some commands that do not work:
- balance (&bal)
- profile (&prof)
- help (&help)
- inventory (&inv)
- usespell (&usespell) [PROBABLY NOT IMPLEMENTED]
- diceroll (&diceroll)
- replit-user (&replit)
- info (&info)
- leaderboard (&lb)
- quest (&q) [PROBABLY NOT IMPLEMENTED]

**Comment by cursorweb** [comment]
strange, they work for me.

**Comment by cursorweb** [comment]
![image](https://user-images.githubusercontent.com/29520825/115640240-17c19700-a2dc-11eb-8bc2-5611f61f4c67.png)


perhaps replit went down?

**Comment by cursorweb** [comment]
oh i see the error

- the commands didn't load properly
this is a common mistake when one of the command files do not contain the `Command` file. Perhaps `use-spell.ts` caused it. Thanks!
