### ISSUE TITLE
Inefficient Database

### ISSUE THREAD

**Issue by cursorweb** [cursorweb/Cycle-Bot-Game#38]
Currently, the database is storing many users that potentially won't even play in those 10 minute timestamps, very memory inefficient.

As cycle grows, this becomes more evident.

## Solution
At the start of each *tick* (every 10 minutes)
- [ ] The database will start empty
- [ ] When a user uses a data-demanding call, get the data from the database
- [ ] For each key, set the user.
- [ ] Empty the database.

## Problem
&admin-git-stash will no longer be usable, but it should be fine

## Caveat
Emptying the database each 10 minutes may be inefficient as the player could play for longer than 10 minutes. @AltariasMainAccount any suggestions?

**Comment by AltariasMainAccount** [comment]
You could attempt to make the pseudo database and the real database interact with eachother. Otherwise this is a great idea.

**Comment by cursorweb** [comment]
hmm what do you mean?

**Comment by AltariasMainAccount** [comment]
You save the current state of the database to the one on firebase (every hour or so). Then you only pull the stuff you need every 10 minutes into the pseudo database and edit that one.

**Comment by cursorweb** [comment]
I see

**Comment by alanlichen** [comment]
Would a js map help any?

**Comment by AltariasMainAccount** [comment]
Fix when?

**Comment by alanlichen** [comment]
I recommend getting Redis as a caching layer. This way, you don't need to use a JSON file or a JS object as a PDB. You can use Redis labs then connect from Repl. I recommend you push to firebase every like 15 ish minutes from Redis.

**Comment by cursorweb** [comment]
seems done to me
