### ISSUE TITLE
Second Major Update

### ISSUE THREAD

**Issue by cursorweb** [cursorweb/Cycle-Bot-Game#39]
Includes things from the previous ones, and new ones.
- [x] Quests
  - [x] How to implement?
- [ ] Lock some commands to levels
- [ ] Add 'enchanting' (boost your items with the cost of levels, you must have 'enchanting book' to use)
- [x] Add 'biomes' aka 'social media'
  - [x] New Prestige
  - [x] Gets exponentially higher to be able to go to the next social media
  - [x] Reset all of your items for a boost
  - [x] Get lots of chests!
- [x] Add 'trivia' (answer questions to get some text)
- [ ] Add 'languages' (requires levels AND cycles) ... buy a new one to get specific boosts.
- [x] Add your spot on the leaderboard even if you aren't on the first page.
- [x] Limit amount in each chest
  - [x] Too many items each time ... but what do you think?
- [x] Nerf levels (linear)
- [ ] Add emoji icons
  - [ ] Inventory
  - [ ] Coding
  - [ ] Posting
  - [ ] Drops
- [x] Serialize usernames (you know who you are)
- [x] Add more ways to get XP
- [ ] Quality of life update
  - [x] Revamp help
  - [ ] Revamp designs
  - [ ] Revamp errors
  - [x] Make it easier to make giveaways
  - [x] Make the logs not dm people
- [x] PEOPLE WHO USE SOCIAL MEDIA AND RESET PROBABLY ACTUALLY GET THEIR ACCOUNTS RESET

**Comment by AltariasMainAccount** [comment]
Do not lock commands to levels.
It is already way too difficult to properly level up to level 5.

**Comment by cursorweb** [comment]
oh

how do you want to change the levels then
should it be linear

**Comment by AltariasMainAccount** [comment]
Make the exp gain better.

**Comment by cursorweb** [comment]
ok i'll make it linear

**Comment by cursorweb** [comment]
Hello, I have absolutely no experience with making icons whatsoever, so if anyone would like to volunteer for making icons, it would be much appreciated.

**Comment by AltariasMainAccount** [comment]
Need info for it, drop it on discord.

**Comment by alanlichen** [comment]
> ok i'll make it linear

Personally, im not a fan of linear because eventually it will become almost impossible. the issue here is that you would have to manually insert stuff, which I'm sure you arent interested in. but maybe you are because you did it for the shop

**Comment by cursorweb** [comment]
1. insert what things?

**Comment by alanlichen** [comment]
Manually inserting xp per level

**Comment by cursorweb** [comment]
??? i'll just make levels worth more maybe? idk

**Comment by AltariasMainAccount** [comment]
### General
The only thing that should generally be changed is the way the game interacts with Code to Cycle conversion.
I feel like it isn't very balanced, sometimes giving too little for too much effort. I have the strongest items multiple times
yet I average at most 250k-400k per 10 minutes.

### Chests/Crates
More types of crates, like a crate for leveling up.
Loot of crates should be toned down, however the rarer the crate is the more loot it should give.
Vote Crates, while being a good incentive to get the people to vote, aren't a good concept. Most of the items you
get from vote crates are easily obtained in bulk from, example, crafting normal crates and unpacking them.

Some crates should also be able to drop cycles, while others should not. (Like the craftable one should not)

### Levels
Levels still do not have a real use, they do not grant anything.
While we are going to restrict commands behind the levels, there should be an incentive to get levels.

Prestige should require a certain level for each different level of prestige (LVL 1 Prestige - LVL 10 | LVL 2 Prestige - LVL 20).
- Prestige will obviously give the better boosts than the idea below, no questions.

You should gain a boost for leveling past a certain point (Like 1% for every 2-3 levels | boost to coding and posting)
- Like at LVL 2 = 1% Boost, LVL 4 = 2% Boost etc.

**Comment by cursorweb** [comment]
1. alright, I will rethink the cycle graph
2. that's a good incentive, and vote crates will be buffed. Vote crates will probably drop cycles
3. Boosts? Aren't those temporary?

**Comment by AltariasMainAccount** [comment]
While boosts are temporary, they are also stronger.
You know how you get that hard coded boost when you are on the official discord server?
Yea, think of it kinda like that, but weaker than the boosts that you can purchase and depending on the level.
This would give players a reason to go for levels instead of simply going for the idle things (like I am doing)

**Comment by alanlichen** [comment]
Since the bot is already in discord.js v13, I wonder if we could make a QOL update to use buttons instead of reactions, especially in the carousal function. I could help transition :)

**Comment by cursorweb** [comment]
yes please, i took a look with the buttons (as can be seen on the discord) but was unable to find how to handle the reaction collection

**Comment by alanlichen** [comment]
> yes please, i took a look with the buttons (as can be seen on the discord) but was unable to find how to handle the reaction collection
It should be as simple as a [message component collector](https://discord.js.org/#/docs/discord.js/stable/class/Message?scrollTo=createMessageComponentCollector)

I am busy tonight I will get to it asap though.

**Comment by cursorweb** [comment]
Here's what I'm thinking quests do (after a long time lol)

* You invest a certain amount of cycles
  * 1,000 for easy quests (little reward) 24 hours to complete
  * 100,000 for medium quests (okay reward) 12 hours to complete
  * 1,000,000 for hard quests (best rewards) 6 hours to complete
* You get hard to obtain items, etc
* After quest completion, you have a cooldown of 24 hours before doing another one
* If you fail a quest you have a cooldown of 48 hours

what do you guys think?

**Comment by lafkpages** [comment]
kewl

**Comment by alanlichen** [comment]
What would be some examples of easy/medium/hard quests? Additionally, some of us are billionaires; the 1m wouldn't affect us much, as (personally) I get 164k per &code.

**Comment by cursorweb** [comment]
1. easy medium and hard just affect how much time you have to complete
2. the quests are a percentage of your score, like double your texts or double your cycles

**Comment by cursorweb** [comment]
The rest of these things are not things I wish to add to cycle bot.

I'm not sure what exactly 'enchanting' is, and more discussion will have to be made on that.
Languages sounds a lot like social media, and it'll just make balancing hard.
Locking commands to levels has been shown to be a bad idea


For now I'm going to work on balancing cycle.
