### ISSUE TITLE
Leaderboard is broken

### ISSUE THREAD

**Issue by PyNonOfReplit** [cursorweb/Cycle-Bot-Game#58]
## Leaderboard is broken
In the second page of the leaderboard, there’s a big step down between 5 million and 10,000 cycles and all the users in between are shown in way later pages (I had 1.5 million and was shown on the 7th or 8th page at 80th rank). Also neverUsedDiscord had 80 billion cycles or so but was shown in the 70s.

**Comment by cursorweb** [comment]
fixed
