### ISSUE TITLE
Items

### ISSUE THREAD

**Issue by cursorweb** [cursorweb/Cycle-Bot-Game#6]
- [x] Utilize the wiki to think of items
- [x] Add a way to get these items from item drops
- [x] Start implementing opening them
- [x] Design inventory
- [x] Add opening/using items
- [x] Finalize

**Comment by alanlichen** [comment]
I believe that "Design inventory" and "Add opening/using items" are done now :)

**Comment by cursorweb** [comment]
Yes :) thanks!
