### ISSUE TITLE
Shop Features

### ISSUE THREAD

**Issue by cursorweb** [cursorweb/Cycle-Bot-Game#7]
- [x] Add CPM setInterval (I know, does drift, but I don't think anyone will notice (hopefully))
- [x] Add CPM shop
  - [x] Refer to #6 for more
  - [x] Remember it's ego coins!
- [x] Add crafting
  - [x] Remember to tax ego coins!
- [x] Also remember to maintain Text and Post shops
- [x] Make the shop nicer
  - [x] Parse Commas
  - [x] 0 args means we print out the available shop pages

**Comment by alanlichen** [comment]
Please check off "Parse Commas" :)
Also, why'd you say "I don't think anyone will notice (hopefully))"? NOW EVERYONE KNOWS!!!!!!!

**Comment by staticvoidliam7** [comment]
cookey

**Comment by cursorweb** [comment]
ok

**Comment by cursorweb** [comment]
not going to tax ego coins that's dumb
